name: lemon_byte
description: Utility library for writing and reading to a byte array
version: 1.0.49
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-byte

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.16.0

