name: lemon_byte
description: Utility library for writing and reading to a byte array
version: 1.0.10
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-byte

environment:
  sdk: '>=2.16.1 <3.0.0'


